# -*- coding: utf-8 -*-
"""Practical 2a: Deep Feedforward Networks

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/deep-learning-indaba/indaba-pracs-2019/blob/master/2a_deep_nets.ipynb

# Practical 2a: Deep Feed-forward Networks

© Deep Learning Indaba. Apache License 2.0.

## Introduction
In this practical, we implement and train a feed-forward neural network (also known as an "MLP" for "multi-layer perceptron") on a dataset called "Fashion MNIST", consisting of small greyscale images of items of fashion. We consider the practical issues around generalisation to out-of-sample data and introduce some important techniques for addressing this.

## Learning Objectives
* Understand how to use **Tensorflow Eager** and **Keras Layers** to build a neural network architecture
* Understand how a model is trained and evaluated
* Be able to explain why there is a difference between **in-sample** and **out-of-sample** model performance
* Understand the concept of **train/validation/test split** and why it's useful
* Research at least 1 technique that can be used to improve model **generalisation**
"""

# Commented out IPython magic to ensure Python compatibility.
#@title Imports (RUN ME!) { display-mode: "form" }

# !pip install tensorflow-gpu==2.0.0-beta0 > /dev/null 2>&1

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

print("TensorFlow executing eagerly: {}".format(tf.executing_eagerly()))

"""## The Data

In this practical, we use the Fashion MNIST dataset consisting of 70,000 greyscale images and their labels. The dataset is divided
 into 60,000 training images and 10,000 test images. The idea is to train a **classifier** to identify the class value (what type of fashion item it is) given the image. We train and *tune* a model on the 60,000 training images and then evaluate how well it classifies the 10,000 test images that the model did not see during training. This task is an example of a **supervised learning** problem, where we are given both input and labels (targets) to learn from. This is in contrast to **unsupervised learning** where we only have inputs from which to learn patterns or **reinforcement learning** where an agent learns how to maximise a reward signal through interaction with its environment.
"""


# Tensorflow has convenient modules for loading a number of standard datasets
fashion_mnist = tf.keras.datasets.fashion_mnist
(train_and_validation_images, train_and_validation_labels), (test_images, test_labels) = fashion_mnist.load_data()

# Prepare Test Data
test_images_tensor = tf.convert_to_tensor(test_images, dtype=tf.float32) / 255.0
test_labels_tensor = tf.convert_to_tensor(test_labels, dtype=tf.int32)
# Create batched test dataset for consistency with validation logic if needed, 
# or use full-batch evaluation as per original code. The original code used full batch.
# We'll pass the tensors directly to our new test_step.


text_labels = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat', 'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

"""###Optional extra reading: Train/Validation/Test Split

When we build machine learning models, the goal is to build a model that will perform well on *future* data that we have not seen yet. We say that we want our models to be able to **generalise** well from whatever training data we can collect and do have available, to whatever data we will be applying them to in future. To do this, we split whatever data we have available into a **training set, a validation set and a test set**. The idea is that we train our model and use the performance on the validation set to make any adjustments to the model and its hyperparameters, but then we report the final accuracy on the test set. The test set (which we never train on), therefore acts as a proxy for our future data.

### Construct a validation set
Next, we remove 10,000 images and labels from the training set to use as a validation set. We will come back to the validation set later!
"""

# Construct a validation set from the last 10000 images and labels from
# train_and_validation_images and train_and_validation_labels
validation_images = train_and_validation_images[-10000:, :, :]
validation_labels = train_and_validation_labels[-10000:]

# Construct a training set from the first 50000 images and labels.
train_images = train_and_validation_images[:50000, :, :]
train_labels = train_and_validation_labels[:50000]

"""### What does the data look like?
Each image in the dataset consists of a 28 x 28 matrix of greyscale pixels. The values are between 0 and 255 where 0 represents black, 255 represents white and there are many shades of grey in-between. Each image is assigned a corresponding numerical label, so the image in ```train_images[i]``` has its corresponding label stored in ```train_labels[i]```. We also have a lookup array called ```text_labels``` to associate a text description with each of the numerical labels. For example, the label 1 is associated with the text description "Trouser".

The 2 cells below demonstrate how to visualise the input data. Make sure you understand what's happening, particularly how the indices correspond to individual items in the dataset.
"""

# We use the Matplotlib plotting library to visualise an image selected at random from the training set
plt.figure()
random_index = np.random.randint(0, len(train_images))
plt.imshow(train_images[random_index], cmap='gray_r')
plt.colorbar()
numerical_label = train_labels[random_index]
text_description = text_labels[numerical_label]
plt.title('True Class: {} ("{}")'.format(numerical_label, text_description))

plt.gca().grid(False)

# Another view, showing 25 randomly selected images at a time
plt.figure(figsize=(10,10))
for i in range(25):
    plt.subplot(5,5,i+1)
    plt.xticks([])
    plt.yticks([])
    plt.grid(False)

    img_index = np.random.randint(0, 50000)
    plt.imshow(train_images[img_index], cmap="gray_r")
    plt.xlabel(text_labels[train_labels[img_index]])

"""### Exploratory Task
Run the above cells multiple times to get a good sense of the dataset. Look at the general structure of the images and their corresponding labels. Can you spot some classes that might be difficult for a classifier to distinguish? If so, why do you think they would be difficult to distinguish? Chat to your neighbour about this.

### Preparing the data with TensorFlow
At the moment, our training data consists of two large tensors. The images are stored in a tensor of shape $[50000, 28, 28]$, consisting of all the $28 \times 28$ images matrices stacked together. The labels are stored in a 1D vector of shape $[50000]$. We wish to train a model using **mini-batch stochastic gradient descent**. In order to do so, we need to shuffle the data and split it into smaller (mini-)batches. We also convert the data from numpy arrays to TensorFlow Tensors.

#### Questions
* Can you explain what the difference is between normal stochastic gradient descent and "batched" stochastic gradient descent? What is the purpose of chunking data into batches during training? Are there any trade-offs? What are they? **HINT**: Speak to your neighbours and tutors about this. You can also read [this blog post](https://machinelearningmastery.com/gentle-introduction-mini-batch-gradient-descent-configure-batch-size/) for more details.
* Why is it important to randomise the data before chunking it into batches?

In order to do this batching (and shuffling) we will use the Tensorflow [Dataset API](https://www.tensorflow.org/api_docs/python/tf/data/Dataset), which is a set of simple reusable components that allow you to build efficient data pipelines. Data is said to "stream" through the pipeline, meaning that when something at the output of the pipeline wants data, the pipeline will provide that data as soon as it has enough, rather than waiting to process all the data. This allows you to easily build pipelines that work on large datasets without having to load it all into memory in one go!

We build this pipeline step-by-step:

We start by defining the ```batch_size``` hyperparameter of our model. This hyperparameter controls the sizes of the mini-batches (chunks) of data that we use to train the model. The value you use will affect the memory usage, speed of convergence and potentially also the performance of the model. It also interacts with the *learning rate* used in gradient descent.
"""

batch_size = 128

"""The first component we add will group the image and label tensors together into a tuple and then split them into individual entries - ie. 50000 tuples containing a (28, 28) dimensional image and 1D label associated with that image. The following line adds this splitting component to the pipeline."""

train_ds = tf.data.Dataset.from_tensor_slices((train_images, train_labels))

"""The next thing we do is apply a map operation. This lets us run an arbitrary function on each element. The function we provide returns the image values divided by 255 and converted ('cast') to a float and the label converted to a 32-bit integer.

**NOTE**: "Lambda" functions are just one-line, anonymous functions. In this case, it defines a function that takes arguments x and y (before the colon), and outputs their manipulated values (after the colon).
"""

# Divide image values and cast to float so that they end up as a floating point number between 0 and 1
train_ds = train_ds.map(lambda x, y: (tf.cast(x, tf.float32) / 255.0, tf.cast(y, tf.int32)))

"""Then we add a **shuffle** component. This returns a random element from the pipeline. Can you spot a potential problem here?

**QUESTION**:  What might happen if the shuffle component didn't have a *buffer*?  **HINT**: Refer back to the discussion about the data pipeline and "data streaming through it" above.
"""

# Shuffle the examples.
train_ds = train_ds.shuffle(buffer_size=batch_size * 10)

"""The final component in our pipeline is the batch component. This just requests `batch_size` elements from the previous pipeline component, groups them together into a single tensor and returns that."""

# Now "chunk" the examples into batches
train_ds = train_ds.batch(batch_size)

# The output of this pipeline will be tuples of tensors containing images and labels.
# The images will be of shape (batch_size, 28, 28) and the labels of shape (batch_size, )

"""Finally, we apply the same pre-processing (converting to Tensors and normalising the values to lie between 0 and 1) to the validation set."""

# Don't worry about this for now, we will use the validation set later
val_ds = tf.data.Dataset.from_tensor_slices((validation_images, validation_labels))
val_ds = val_ds.map(lambda x, y: (tf.cast(x, tf.float32) / 255.0, tf.cast(y, tf.int32)))
# BATCHING VALIDATION SET:
# We must batch the validation data just like the training data.
# This ensures that the model receives inputs with the expected shape (batch_size, 28, 28)
# instead of individual images, preventing shape mismatch errors during evaluation.
val_ds = val_ds.batch(batch_size)


# ==============================================================================
# Refactored Code for Experiments: Baseline, Dropout, Batch Normalization
# ==============================================================================

def create_model(use_dropout=False, use_batchnorm=False):
    """
    Creates a Keras Sequential model with optional Dropout and Batch Normalization.
    """
    layers = [tf.keras.layers.Flatten(input_shape=(28, 28), name='flatten_input')]
    
    # --- Hidden Layer 1 ---
    if use_batchnorm:
        # Batch Norm is typically applied before activation
        layers.append(tf.keras.layers.Dense(256, use_bias=False, name='input_to_hidden1_linear'))
        layers.append(tf.keras.layers.BatchNormalization(name='hidden1_bn'))
        layers.append(tf.keras.layers.Activation('relu', name='input_to_hidden1_relu'))
    else:
        layers.append(tf.keras.layers.Dense(256, activation='relu', name='input_to_hidden1'))
    
    if use_dropout:
        layers.append(tf.keras.layers.Dropout(0.5, name='hidden1_dropout'))

    # --- Hidden Layer 2 ---
    if use_batchnorm:
        layers.append(tf.keras.layers.Dense(128, use_bias=False, name='hidden1_to_hidden2_linear'))
        layers.append(tf.keras.layers.BatchNormalization(name='hidden2_bn'))
        layers.append(tf.keras.layers.Activation('relu', name='hidden1_to_hidden2_relu'))
    else:
        layers.append(tf.keras.layers.Dense(128, activation='relu', name='hidden1_to_hidden2'))
        
    if use_dropout:
        layers.append(tf.keras.layers.Dropout(0.5, name='hidden2_dropout'))

    # --- Output Layer ---
    layers.append(tf.keras.layers.Dense(10, name='hidden_to_logits'))
    
    return tf.keras.Sequential(layers)


def run_experiment(name, model, train_ds, val_ds, num_epochs=20):
    """
    Runs training and validation for a specific model configuration.
    """
    print(f"\nStarting Experiment: {name}")
    print("-" * 40)
    
    optimizer = tf.keras.optimizers.Adam()
    loss_object = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
    
    train_loss = tf.keras.metrics.Mean(name='train_loss')
    train_accuracy = tf.keras.metrics.SparseCategoricalAccuracy(name='train_accuracy')
    val_loss = tf.keras.metrics.Mean(name='val_loss')
    val_accuracy = tf.keras.metrics.SparseCategoricalAccuracy(name='val_accuracy')
    
    # Define steps inside to capture specific model/optimizer instances and avoid reusing @tf.function traces
    @tf.function
    def train_step(image, label):
        with tf.GradientTape() as tape:
            logits = model(image, training=True)
            loss = loss_object(label, logits)
        gradients = tape.gradient(loss, model.trainable_variables)
        optimizer.apply_gradients(zip(gradients, model.trainable_variables))
        train_loss(loss)
        train_accuracy(label, logits)

    @tf.function
    def val_step(image, label):
        logits = model(image, training=False)
        loss = loss_object(label, logits)
        val_loss(loss)
        val_accuracy(label, logits)
    

    @tf.function
    def test_step(image, label):
        logits = model(image, training=False)
        t_loss = loss_object(label, logits)
        return t_loss, logits

    history = {
        'train_loss': [],
        'train_acc': [],
        'val_loss': [],
        'val_acc': [],
        'test_loss': None,
        'test_acc': None
    }
    
    for epoch in range(num_epochs):
        train_loss.reset_state()
        train_accuracy.reset_state()
        val_loss.reset_state()
        val_accuracy.reset_state()
        
        for image, label in train_ds:
            train_step(image, label)
            
        for image, label in val_ds:
            val_step(image, label)
            
        print(f'Epoch {epoch + 1}, '
              f'Loss: {train_loss.result():.3f}, Accuracy: {train_accuracy.result():.3%}, '
              f'Val Loss: {val_loss.result():.3f}, Val Accuracy: {val_accuracy.result():.3%}')
        
        history['train_loss'].append(float(train_loss.result()))
        history['train_acc'].append(float(train_accuracy.result()))
        history['val_loss'].append(float(val_loss.result()))
        history['val_acc'].append(float(val_accuracy.result()))

    # Final Test Evaluation
    print(f"Evaluating {name} on Test Set...")
    test_loss_metric = tf.keras.metrics.Mean(name='test_loss')
    test_acc_metric = tf.keras.metrics.SparseCategoricalAccuracy(name='test_accuracy')
    
    # We use the global test_images_tensor and test_labels_tensor
    t_loss, t_logits = test_step(test_images_tensor, test_labels_tensor)
    test_loss_metric(t_loss)
    test_acc_metric(test_labels_tensor, t_logits)
    
    history['test_loss'] = float(test_loss_metric.result())
    history['test_acc'] = float(test_acc_metric.result())
    print(f"Test Loss: {history['test_loss']:.3f}, Test Accuracy: {history['test_acc']:.3%}")
        
    return history



# --- RUN EXPERIMENTS ---

# 1. Baseline Model
baseline_model = create_model(use_dropout=False, use_batchnorm=False)
baseline_history = run_experiment("Baseline", baseline_model, train_ds, val_ds, num_epochs=20)

# 2. Dropout Model
dropout_model = create_model(use_dropout=True, use_batchnorm=False)
dropout_history = run_experiment("Dropout", dropout_model, train_ds, val_ds, num_epochs=20)

# 3. Batch Normalization Model
batchnorm_model = create_model(use_dropout=False, use_batchnorm=True)
batchnorm_history = run_experiment("Batch Normalization", batchnorm_model, train_ds, val_ds, num_epochs=20)


# --- PLOTTING RESULTS ---

epochs_range = range(1, 21)

# Plot 1: Compare Validation Accuracy
plt.figure(figsize=(10, 6))
plt.plot(epochs_range, baseline_history['val_acc'], label='Baseline Val Acc')
plt.plot(epochs_range, dropout_history['val_acc'], label='Dropout Val Acc')
plt.plot(epochs_range, batchnorm_history['val_acc'], label='BatchNorm Val Acc')
plt.title('Validation Accuracy Comparison')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)
plt.savefig('comparison_accuracy.png')
print("Saved comparison_accuracy.png")

# Plot 2: Compare Validation Loss
plt.figure(figsize=(10, 6))
plt.plot(epochs_range, baseline_history['val_loss'], label='Baseline Val Loss')
plt.plot(epochs_range, dropout_history['val_loss'], label='Dropout Val Loss')
plt.plot(epochs_range, batchnorm_history['val_loss'], label='BatchNorm Val Loss')
plt.title('Validation Loss Comparison')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)
plt.savefig('comparison_loss.png')
print("Saved comparison_loss.png")

# Plot 3: Detailed Training vs Validation for Dropout
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(epochs_range, dropout_history['train_acc'], label='Train Acc')
plt.plot(epochs_range, dropout_history['val_acc'], label='Val Acc')
plt.title('Dropout: Training vs Validation Accuracy')
plt.legend()
plt.grid(True)

plt.subplot(1, 2, 2)
plt.plot(epochs_range, dropout_history['train_loss'], label='Train Loss')
plt.plot(epochs_range, dropout_history['val_loss'], label='Val Loss')
plt.title('Dropout: Training vs Validation Loss')
plt.legend()
plt.grid(True)
plt.savefig('dropout_performance.png')
print("Saved dropout_performance.png")

# Plot 4: Question 1 specific - Baseline Training vs Validation
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(epochs_range, baseline_history['train_acc'], label='Train Acc')
plt.plot(epochs_range, baseline_history['val_acc'], label='Val Acc')
plt.title('Baseline: Training vs Validation Accuracy')
plt.legend()
plt.grid(True)

plt.subplot(1, 2, 2)
plt.plot(epochs_range, baseline_history['train_loss'], label='Train Loss')
plt.plot(epochs_range, baseline_history['val_loss'], label='Val Loss')
plt.title('Baseline: Training vs Validation Loss')
plt.legend()
plt.grid(True)
plt.savefig('baseline_performance.png')
print("Saved baseline_performance.png")